# -*- coding: utf-8 -*-
"""Exploratory_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FxYtofdzOyr_U0q-RDyn_fCwAkdthDM
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("online_retail_II_cleaned.csv")
df.head()

# What are the top 10 products?
top_product = df.pivot_table(index="Description", values="Quantity", aggfunc="sum")
top_product = top_product.sort_values(by="Quantity", ascending=False)
top_ten_products = top_product.head(10)
print(top_ten_products)

# Visualization
plt.figure(figsize=(12, 6))
top_ten_products.plot(kind='bar')
plt.title('Top 10 Best-Selling Products')
plt.xlabel('Product Description')
plt.ylabel('Total Quantity Sold')
plt.xticks(rotation=45, ha='right')
plt.savefig("Top_Ten_Products.png", dpi=300)
plt.show()

df = pd.read_csv("online_retail_II_cleaned.csv")
df.head()

# Which countries contribute the most to sales?
top_country_sales_group = df.groupby("Country")
top_country_sales_sum = top_country_sales_group["Total Revenue"].sum()
top_country_sales = top_country_sales_sum.sort_values(ascending=False)
top_ten_country_sales = top_country_sales.head(10)
print(top_ten_country_sales)

# Visualization
plt.figure(figsize=(12, 6))
top_ten_country_sales.plot(kind='bar')
plt.title('Top 10 Countries by Sales')
plt.xlabel('Country')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.savefig("Top_Ten_Countries.png")
plt.show()